DATASET:
  TRAIN: "datasets/apricot/images/train"
  VAL: "datasets/apricot/images/val"
  NAMES:
    - person
    - bicycle
    - car
    - motorbike
    - aeroplane
    - bicycle
    - bus
    - car
    - motorbike
    - train
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcases
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - sofa
    - pottedplant
    - bed
    - diningtable
    - toilet
    - tvmonitor
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush

MODEL:
  NC: 80
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352

TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTONES:
    - 100
    - 200
    - 250